[project]
name = "sbiaxpdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beartype>=0.22.2",
    "blackjax>=1.2.5",
    "chainconsumer>=0.34.0",
    "cloudpickle>=3.1.1",
    "diffrax>=0.6.1",
    "einops>=0.8.1",
    "equinox>=0.11.10",
    "flowjax>=9.0.0",
    "jax==0.4.33",
    "jax-tqdm>=0.3.1",
    "matplotlib>=3.9.4",
    "ml-collections>=0.1.1",
    "numpy>=2.0.2",
    "optax>=0.2.4",
    "optuna>=4.5.0",
    "plotly>=6.3.1",
    "scikit-learn>=1.6.1",
    "tqdm>=4.67.1",
]
